### ISSUE TITLE
Build failing on 4.3.1 update when the project uses next-intl

### ISSUE THREAD

**Issue by stavros-k** [dc7290/next-export-optimize-images#861]
**Describe the bug**

Updating this package to 4.3.1 causes build to fail with 

```shell
Error: Couldn't find next-intl config file. Please follow the instructions at https://next-intl-docs.vercel.app/docs/getting-started/app-router-server-components
   at t.Z (/home/jenkins/agent/workspace/my-project_PR-77/.next/server/chunks/4.js:1:145311)
    at /home/jenkins/agent/workspace/my-project_PR-77/.next/server/chunks/4.js:1:144465
    at /home/jenkins/agent/workspace/my-project_PR-77/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:185493
    at /home/jenkins/agent/workspace/my-project_PR-77/.next/server/chunks/4.js:1:144689
    at /home/jenkins/agent/workspace/my-project_PR-77/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:185493
    at s (/home/jenkins/agent/workspace/my-project_PR-77/.next/server/chunks/4.js:1:142835)
    at o (/home/jenkins/agent/workspace/my-project_PR-77/.next/server/chunks/4.js:1:143427)
    at M (/home/jenkins/agent/workspace/my-project_PR-77/.next/server/app/[locale]/network/page.js:1:675252)
    at eh (/home/jenkins/agent/workspace/my-project_PR-77/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/home/jenkins/agent/workspace/my-project_PR-77/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671) {
  digest: '2076780070'
}
```

This is the order I use my next.config.mjs

```js
export default withBundleAnalyzer(withExportImages(withNextIntl(nextConfig)));
```

If I change it to 

```js
export default withBundleAnalyzer(withNextIntl(withExportImages(nextConfig)));
```

Build completes, but NO build directory is created at all, resulting in 

```shell
- Image Optimization -
Optimization progress |░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░| 0% || 0/93952 Chunksno9
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open '/home/jenkins/agent/workspace/my-pr{
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/jenkins/agent/workspace/my-project_PR-77/build/optimized-images/7-'
}
```

---

(On a seperate project, with the same issue, changing the order like above, I get this error)
https://github.com/amannn/next-intl/blob/b311ebcf205c4b1e0ed3303bb4c4303c2555f038/packages/next-intl/src/config.tsx#L3

Which should **not** have any connection, but I find it "weird" that the function name matches, and at the same time a same-named function changed here since the last update :D
https://github.com/dc7290/next-export-optimize-images/commit/f5a2805b39a6c886ca73c49b2778818f8b36479c#diff-364a7610368f4cd2af84b32058a71f901c559bcffdba4175a8eafc86fa6e2e32

---

**Note** that CI starts on a clean slate, inside a container, and this specific PR only updates this package, so no other interference.

**To Reproduce**

**Expected behavior**
Build completes succesfully

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dc7290** [comment]
Changing the order may help!

```
export default withExportImages(withBundleAnalyzer(withNextIntl(nextConfig)));
```

**Comment by stavros-k** [comment]
Ah, yes did this and now it seems to work fine!

Thanks!

```js
...
nextConfig = withNextIntl(nextConfig);
nextConfig = withBundleAnalyzer(nextConfig);
nextConfig = withExportImages(nextConfig);
```
